modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL=""

[[mods]]
modId="faidhudscale"
version="${mod_version}"
displayName="First Aid HUD Scale"
authors="${mod_authors}"
description='''First AidのボディHUD(体力表示)のサイズをconfigで変更できるようにするアドオンMOD'''

[[dependencies.faidhudscale]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.faidhudscale]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# First Aid 本体は必須ではないよ
# 入っていない場合、このMODは何もしないだけ
[[dependencies.faidhudscale]]
    modId="firstaid"
    mandatory=false
    versionRange="[1.20.1,)"
    ordering="AFTER"
    side="CLIENT"